name: CI Pipeline

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "packages/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".python-version"

jobs:
  type_check:
    name: Type Check and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.27"
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync --dev --all-extras

      - name: Ruff check
        run: |
          uv run ruff check || exit 1
          uv run ruff format --check || exit 1

      - name: Pyright
        run: uv run pyright .

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: type_check
    environment: LLMGW_SETTINGS
    env:
      UIPATH_LLM_SERVICE: ${{ vars.UIPATH_LLM_SERVICE }}
      LLMGW_URL: ${{ vars.LLMGW_URL }}
      LLMGW_SEMANTIC_ORG_ID: ${{ secrets.LLMGW_SEMANTIC_ORG_ID }}
      LLMGW_SEMANTIC_USER_ID: ${{ secrets.LLMGW_SEMANTIC_USER_ID }}
      LLMGW_SEMANTIC_TENANT_ID: ${{ secrets.LLMGW_SEMANTIC_TENANT_ID }}
      LLMGW_REQUESTING_PRODUCT: ${{ vars.LLMGW_REQUESTING_PRODUCT }}
      LLMGW_REQUESTING_FEATURE: ${{ vars.LLMGW_REQUESTING_FEATURE }}
      LLMGW_CLIENT_ID: ${{ secrets.LLMGW_CLIENT_ID }}
      LLMGW_CLIENT_SECRET: ${{ secrets.LLMGW_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.27"
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync --dev --all-extras

      - name: Run tests
        run: uv run pytest tests
